server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://51.38.134.31:3306/innovate_it_database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: developer
    password: DevDevDev123.
    #driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

connection:
  pool:
    initialPoolSize: 5
    minPoolSize: 5
    maxPoolSize: 5
    maxIdleTime: 3000
